package ch.interlis.iox_j.validator;

import java.util.HashSet;

/** contains all special characters and reserved words in INTERLIS 2.3.
 * the reserved words are always written in capital letters.
 */
public class Ili23KeyWords {
	private static final String ABSTRACT="ABSTRACT";
	private static final String ACCORDING="ACCORDING";
	private static final String AGGREGATES="AGGREGATES";
	private static final String AGGREGATION="AGGREGATION";
	private static final String ALL="ALL";
	private static final String AND="AND";
	private static final String ANY="ANY";
	private static final String ANYCLASS="ANYCLASS";
	private static final String ANYSTRUCTURE="ANYSTRUCTURE";
	private static final String ARCS="ARCS";
	private static final String AREA="AREA";
	private static final String AS="AS";
	private static final String ASSOCIATION="ASSOCIATION";
	private static final String AT="AT";
	private static final String ATTRIBUTE="ATTRIBUTE";
	private static final String ATTRIBUTES="ATTRIBUTES";
	private static final String BAG="BAG";
	private static final String BASE="BASE";
	private static final String BASED="BASED";
	private static final String BASKET="BASKET";
	private static final String BINARY="BINARY";
	private static final String BLACKBOX="BLACKBOX";
	private static final String BLANK="BLANK";
	private static final String BOOLEAN="BOOLEAN";
	private static final String BY="BY";
	private static final String CARDINALITY="CARDINALITY";
	private static final String CIRCULAR="CIRCULAR";
	private static final String CLASS="CLASS";
	private static final String CLOCKWISE="CLOCKWISE";
	private static final String CODE="CODE";
	private static final String CONSTRAINT="CONSTRAINT";
	private static final String CONSTRAINTS="CONSTRAINTS";
	private static final String CONTINUE="CONTINUE";
	private static final String CONTINUOUS="CONTINUOUS";
	private static final String CONTOUR="CONTOUR";
	private static final String CONTRACTED="CONTRACTED";
	private static final String COORD="COORD";
	private static final String COORD2="COORD2";
	private static final String COORD3="COORD3";
	private static final String COUNTERCLOCKWISE="COUNTERCLOCKWISE";
	private static final String DATE="DATE";
	private static final String DEFAULT="DEFAULT";
	private static final String DEFINED="DEFINED";
	private static final String DEGREES="DEGREES";
	private static final String DEPENDS="DEPENDS";
	private static final String DERIVATIVES="DERIVATIVES";
	private static final String DERIVED="DERIVED";
	private static final String DIM1="DIM1";
	private static final String DIM2="DIM2";
	private static final String DIRECTED="DIRECTED";
	private static final String DOMAIN="DOMAIN";
	private static final String END="END";
	private static final String ENUMTREEVAL="ENUMTREEVAL";
	private static final String ENUMVAL="ENUMVAL";
	private static final String EQUAL="EQUAL";
	private static final String EXISTENCE="EXISTENCE";
	private static final String EXTENDED="EXTENDED";
	private static final String EXTENDS="EXTENDS";
	private static final String EXTERNAL="EXTERNAL";
	private static final String FINAL="FINAL";
	private static final String FIRST="FIRST";
	private static final String FIX="FIX";
	private static final String FONT="FONT";
	private static final String FORM="FORM";
	private static final String FORMAT="FORMAT";
	private static final String FREE="FREE";
	private static final String FROM="FROM";
	private static final String FUNCTION="FUNCTION";
	private static final String GRADS="GRADS";
	private static final String GRAPHIC="GRAPHIC";
	private static final String HALIGNMENT="HALIGNMENT";
	private static final String HIDING="HIDING";
	private static final String I16="I16";
	private static final String I32="I32";
	private static final String IDENT="IDENT";
	private static final String IMPORTS="IMPORTS";
	private static final String IN="IN";
	private static final String INHERITANCE="INHERITANCE";
	private static final String INSPECTION="INSPECTION";
	private static final String INTERLIS="INTERLIS";
	private static final String JOIN="JOIN";
	private static final String LAST="LAST";
	private static final String LINE="LINE";
	private static final String LINEATTR="LINEATTR";
	private static final String LINESIZE="LINESIZE";
	private static final String LIST="LIST";
	private static final String LNBASE="LNBASE";
	private static final String LOCAL="LOCAL";
	private static final String MANDATORY="MANDATORY";
	private static final String METAOBJECT="METAOBJECT";
	private static final String MODEL="MODEL";
	private static final String MTEXT="MTEXT";
	private static final String NAME="NAME";
	private static final String NO="NO";
	private static final String NOT="NOT";
	private static final String NULL="NULL";
	private static final String NUMERIC="NUMERIC";
	private static final String OBJECT="OBJECT";
	private static final String OBJECTS="OBJECTS";
	private static final String OF="OF";
	private static final String OID="OID";
	private static final String ON="ON";
	private static final String OPTIONAL="OPTIONAL";
	private static final String OR="OR";
	private static final String ORDERED="ORDERED";
	private static final String OTHERS="OTHERS";
	private static final String OVERLAPS="OVERLAPS";
	private static final String PARAMETER="PARAMETER";
	private static final String PARENT="PARENT";
	private static final String PERIPHERY="PERIPHERY";
	private static final String PI="PI";
	private static final String POLYLINE="POLYLINE";
	private static final String PROJECTION="PROJECTION";
	private static final String RADIANS="RADIANS";
	private static final String REFERENCE="REFERENCE";
	private static final String REFSYSTEM="REFSYSTEM";
	private static final String REQUIRED="REQUIRED";
	private static final String RESTRICTION="RESTRICTION";
	private static final String ROTATION="ROTATION";
	private static final String SET="SET";
	private static final String SIGN="SIGN";
	private static final String STRAIGHTS="STRAIGHTS";
	private static final String STRUCTURE="STRUCTURE";
	private static final String SUBDIVISION="SUBDIVISION";
	private static final String SURFACE="SURFACE";
	private static final String SYMBOLOGY="SYMBOLOGY";
	private static final String TABLE="TABLE";
	private static final String TEXT="TEXT";
	private static final String THATAREA="THATAREA";
	private static final String THIS="THIS";
	private static final String THISAREA="THISAREA";
	private static final String TID="TID";
	private static final String TIDSIZE="TIDSIZE";
	private static final String TO="TO";
	private static final String TOPIC="TOPIC";
	private static final String TRANSFER="TRANSFER";
	private static final String TRANSIENT="TRANSIENT";
	private static final String TRANSLATION="TRANSLATION";
	private static final String TYPE="TYPE";
	private static final String UNDEFINED="UNDEFINED";
	private static final String UNION="UNION";
	private static final String UNIQUE="UNIQUE";
	private static final String UNIT="UNIT";
	private static final String UNQUALIFIED="UNQUALIFIED";
	private static final String URI="URI";
	private static final String VALIGNMENT="VALIGNMENT";
	private static final String VERSION="VERSION";
	private static final String VERTEX="VERTEX";
	private static final String VERTEXINFO="VERTEXINFO";
	private static final String VIEW="VIEW";
	private static final String WHEN="WHEN";
	private static final String WHERE="WHERE";
	private static final String WITH="WITH";
	private static final String WITHOUT="WITHOUT";
	
	private Ili23KeyWords() {
		// empty
	}

	public static HashSet<String> getAllKeyWords() {
		HashSet<String> keyWords=new HashSet<String>();
		keyWords.add(ABSTRACT);
		keyWords.add(ACCORDING);
		keyWords.add(AGGREGATES);
		keyWords.add(AGGREGATION);
		keyWords.add(ALL);
		keyWords.add(AND);
		keyWords.add(ANY);
		keyWords.add(ANYCLASS);
		keyWords.add(ANYSTRUCTURE);
		keyWords.add(ARCS);
		keyWords.add(AREA);
		keyWords.add(AS);
		keyWords.add(ASSOCIATION);
		keyWords.add(AT);
		keyWords.add(ATTRIBUTE);
		keyWords.add(ATTRIBUTES);
		keyWords.add(BAG);
		keyWords.add(BASE);
		keyWords.add(BASED);
		keyWords.add(BASKET);
		keyWords.add(BINARY);
		keyWords.add(BLACKBOX);
		keyWords.add(BLANK);
		keyWords.add(BOOLEAN);
		keyWords.add(BY);
		keyWords.add(CARDINALITY);
		keyWords.add(CIRCULAR);
		keyWords.add(CLASS);
		keyWords.add(CLOCKWISE);
		keyWords.add(CODE);
		keyWords.add(CONSTRAINT);
		keyWords.add(CONSTRAINTS);
		keyWords.add(CONTINUE);
		keyWords.add(CONTINUOUS);
		keyWords.add(CONTOUR);
		keyWords.add(CONTRACTED);
		keyWords.add(COORD);
		keyWords.add(COORD2);
		keyWords.add(COORD3);
		keyWords.add(COUNTERCLOCKWISE);
		keyWords.add(DATE);
		keyWords.add(DEFAULT);
		keyWords.add(DEFINED);
		keyWords.add(DEGREES);
		keyWords.add(DEPENDS);
		keyWords.add(DERIVATIVES);
		keyWords.add(DERIVED);
		keyWords.add(DIM1);
		keyWords.add(DIM2);
		keyWords.add(DIRECTED);
		keyWords.add(DOMAIN);
		keyWords.add(END);
		keyWords.add(ENUMTREEVAL);
		keyWords.add(ENUMVAL);
		keyWords.add(EQUAL);
		keyWords.add(EXISTENCE);
		keyWords.add(EXTENDED);
		keyWords.add(EXTENDS);
		keyWords.add(EXTERNAL);
		keyWords.add(FINAL);
		keyWords.add(FIRST);
		keyWords.add(FIX);
		keyWords.add(FONT);
		keyWords.add(FORM);
		keyWords.add(FORMAT);
		keyWords.add(FREE);
		keyWords.add(FROM);
		keyWords.add(FUNCTION);
		keyWords.add(GRADS);
		keyWords.add(GRAPHIC);
		keyWords.add(HALIGNMENT);
		keyWords.add(HIDING);
		keyWords.add(I16);
		keyWords.add(I32);
		keyWords.add(IDENT);
		keyWords.add(IMPORTS);
		keyWords.add(IN);
		keyWords.add(INHERITANCE);
		keyWords.add(INSPECTION);
		keyWords.add(INTERLIS);
		keyWords.add(JOIN);
		keyWords.add(LAST);
		keyWords.add(LINE);
		keyWords.add(LINEATTR);
		keyWords.add(LINESIZE);
		keyWords.add(LIST);
		keyWords.add(LNBASE);
		keyWords.add(LOCAL);
		keyWords.add(MANDATORY);
		keyWords.add(METAOBJECT);
		keyWords.add(MODEL);
		keyWords.add(MTEXT);
		keyWords.add(NAME);
		keyWords.add(NO);
		keyWords.add(NOT);
		keyWords.add(NULL);
		keyWords.add(NUMERIC);
		keyWords.add(OBJECT);
		keyWords.add(OBJECTS);
		keyWords.add(OF);
		keyWords.add(OID);
		keyWords.add(ON);
		keyWords.add(OPTIONAL);
		keyWords.add(OR);
		keyWords.add(ORDERED);
		keyWords.add(OTHERS);
		keyWords.add(OVERLAPS);
		keyWords.add(PARAMETER);
		keyWords.add(PARENT);
		keyWords.add(PERIPHERY);
		keyWords.add(PI);
		keyWords.add(POLYLINE);
		keyWords.add(PROJECTION);
		keyWords.add(RADIANS);
		keyWords.add(REFERENCE);
		keyWords.add(REFSYSTEM);
		keyWords.add(REQUIRED);
		keyWords.add(RESTRICTION);
		keyWords.add(ROTATION);
		keyWords.add(SET);
		keyWords.add(SIGN);
		keyWords.add(STRAIGHTS);
		keyWords.add(STRUCTURE);
		keyWords.add(SUBDIVISION);
		keyWords.add(SURFACE);
		keyWords.add(SYMBOLOGY);
		keyWords.add(TABLE);
		keyWords.add(TEXT);
		keyWords.add(THATAREA);
		keyWords.add(THIS);
		keyWords.add(THISAREA);
		keyWords.add(TID);
		keyWords.add(TIDSIZE);
		keyWords.add(TO);
		keyWords.add(TOPIC);
		keyWords.add(TRANSFER);
		keyWords.add(TRANSIENT);
		keyWords.add(TRANSLATION);
		keyWords.add(TYPE);
		keyWords.add(UNDEFINED);
		keyWords.add(UNION);
		keyWords.add(UNIQUE);
		keyWords.add(UNIT);
		keyWords.add(UNQUALIFIED);
		keyWords.add(URI);
		keyWords.add(VALIGNMENT);
		keyWords.add(VERSION);
		keyWords.add(VERTEX);
		keyWords.add(VERTEXINFO);
		keyWords.add(VIEW);
		keyWords.add(WHEN);
		keyWords.add(WHERE);
		keyWords.add(WITH);
		keyWords.add(WITHOUT);
		return keyWords;
	}
}